### ISSUE TITLE
'Garbage' waifu folder

### ISSUE THREAD

**Issue by LeCleric** [SeanMarcoux/waifu-bot#4]
If anyone wants to post an unrelated image they can set the incoming waifu to garbage.

- Contents are either deleted or sent images are simply ignored
- Will default to 'Garbage' folder if there have not been any incoming waifus for 5 minutes

**Comment by SeanMarcoux** [comment]
We already have a Misc folder that can handle the garbage. I'm cool with it getting random screenshots. At worst, I can clean it out if people want to use the misc folder for real stuff. I added the five minute inactivity timer
